### ISSUE TITLE
Cant import 'Terminal' on Arch linux running python 2.7.9

### ISSUE THREAD

**Issue by skinney6** [erikrose/blessings#106]
```
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from blessings import Terminal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "blessings.py", line 2, in <module>
    from blessings import Terminal
ImportError: cannot import name Terminal
```

Works fine on my Ubuntu 14.10 with pyton 2.7.6
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from blessings import Terminal
>>> t = Terminal()
>>> print t.bold('Hi There')
Hi There
```

**Comment by jquast** [comment]
Hi @skinney6 thanks a lot for the report! In your Arch Linux error, it reads,

``  File "blessings.py", line 2, in <module>``

Do I suspect correctly that ``blessings.py`` is your own program? There is no such ``blessings.py`` distributed by the package. Could you please execute the following commands and report its output?

```
import blessings
print(blessings.__file__)
```

**Comment by skinney6** [comment]
Somthing in blessings.py was goofing it up. I didn't realize that would interfere with an interactive session.
Sorry to bother you.

**Comment by jquast** [comment]
Not a problem, enjoy!
